init:
  cfgData: $Cat('app/config.json')
  cfg: $AsJSON($cfgData)

pipeline:
  init:
    action: print
    message: init system
  create:
    action: msg:setupResource
    resources:
      - URL: $triggerBucket
        type: topic
        vendor: gcp
        credentials: $gcpCredentials
      - URL: $triggerBucket
        type: subscription
        vendor: gcp
        credentials: $gcpCredentials
        config:
          topic:
            URL: /projects/${projectID}/topics/${triggerBucket}
  setupBucket:
    triggerBucket:
      isDir: true
      action: storage:create
      dest:
        URL: gs://${triggerBucket}/
        credentials: $gcpCredentials

#  setupNotification:
#    action: gcp/storage:setNotification
#    credentials: $gcpCredentials
#    bucket: $triggerBucket
#    topic: $topic
#    payloadFormat: JSON_API_V1
#    eventTypes:
#      - OBJECT_FINALIZE

  deployConfig:
    action: storage:upload
    sourceKey: cfg
    dest:
      URL: gs://${configBucket}/BitsyV1/config.json
      credentials: $gcpCredentials
