pipeline:
  setupNotification:
    action: gcp/storage:setNotification
    credentials: viant-dataflow

    bucket: viant_dataflow_bitsy
    topic: bitsy
    payloadFormat: JSON_API_V1
    eventTypes:
      - OBJECT_FINALIZE